libname libsas excel "C:\Wallpaper\LungCapData.xls";
DATA TOAD;
	INFILE 'C:\Course\MIS 6334 - ABI\SAS workdirectory\toadjump.dat';
	INPUT Name $ height1 height2 height3 height4 ;
run;
DATA uspresidents;
   INFILE 'c:\Course\MIS 6334 - ABI\SAS workdirectory\USPresidents.dat';
   INPUT President $ Party $ Number 1.1;
RUN;
PROC PRINT Data=Toad;
	Title 'Toadsie';
Run;
proc print data=uspresidents;
	title 'uspresidents';
run;
data contest;
	infile 'C:\Course\MIS 6334 - ABI\SAS workdirectory\Pumpkin.dat';
	input Name $16. Age 3. +1 Type $1. +1 Date MMDDYY10. (Score1 Score2 Score3 Score4 Score5) (4.1);
run;
proc print data=contest;
	title 'Pumpkin contest';
run;
Data NationalParks;
	infile 'C:\Course\MIS 6334 - ABI\SAS workdirectory\natpark.dat';
	input ParkName $ 1-22 State $ Year @40 Acreage COMMA9.;
run;
proc print data = NationalParks;
	title 'Selected National Parks';
run;
Data Resultscanoe;
	infile 'C:\Course\MIS 6334 - ABI\SAS workdirectory\Canoes.dat';
	input @'School:' SchoolName $ @'Time:' Racetime :STIMER8.;
run;
proc print data=Resultscanoe;
run;
